import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

// One canonical source skill, emitted to the two portable host locations
// (.claude for Claude, .agents for Codex/agents) and embedded into the binary so
// `wux-review skills show` (and `install.sh --with-skills`) can extract it on a
// host with no repo checkout. Regenerating must be a no-op when nothing changed.
const repoRoot = join(import.meta.dir, "..");
const source = join(repoRoot, "skills", "wux-review", "SKILL.md");

const portableTargets = [
  join(repoRoot, ".claude", "skills", "wux-review", "SKILL.md"),
  join(repoRoot, ".agents", "skills", "wux-review", "SKILL.md"),
];
const embeddedTarget = join(repoRoot, "src", "skills", "embedded.ts");

async function writeIfChanged(path: string, content: string): Promise<void> {
  let existing: string | undefined;
  try {
    existing = await readFile(path, "utf8");
  } catch {
    existing = undefined;
  }
  if (existing === content) {
    return;
  }
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, "utf8");
}

function renderEmbedded(content: string): string {
  return `// Generated by scripts/generate-skills.ts. Do not edit by hand.

export const SKILLS: Readonly<Record<string, string>> = {
  "wux-review": ${JSON.stringify(content)},
};
`;
}

async function main(): Promise<void> {
  const content = await readFile(source, "utf8");
  for (const target of portableTargets) {
    await writeIfChanged(target, content);
  }
  await writeIfChanged(embeddedTarget, renderEmbedded(content));
}

await main();
